version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
        depends_on:
            - php
    
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
    
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_USER: ${DB_USERNAME:-laravel_user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-laravel_password}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:8080"
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql

volumes:
    mysql:
    src: