version: '3.7'

services:
    nginx:
        build:
            context: ./docker/nginx
        container_name: nginx
        ports:
            - "8000:80"
        depends_on:
            - php
        volumes:
            - ./src/:/home/source/main
    
    php:
        build:
            context: ./docker/php
        container_name: php
        restart: unless-stopped
        healthcheck:
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 30s
            test: ["CMD", "curl", "-f", "http://localhost:8000"]
        depends_on:
            - mysql
        volumes:
            - ./src/:/home/source/main
        working_dir: /home/source/main
    
    mysql:
        image: mysql:8.0
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        platform: linux/x86_64
        ports:
            - "3306:3306"
        volumes:
            - mysql-volumes:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-toor}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
            MYSQL_USER: ${MYSQL_USER:-laravel_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-laravel_pwd}
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-toor}
            MYSQL_USER: ${MYSQL_USER:-laravel_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-laravel_pwd}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
            
volumes:
    mysql-volumes:

networks:
    default:
        name: php-netword